use crate::{
    config::{self, Config},
    hypr,
};
use anyhow::{Context, Result, ensure};
use std::{
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

const START: &str = "-- BEGIN OMARCHY CURSOR";
const END: &str = "-- END OMARCHY CURSOR";
fn config_root() -> Result<PathBuf> {
    Ok(config::dir()?.parent().unwrap().to_path_buf())
}
fn binary() -> Result<PathBuf> {
    Ok(config::home()?.join(".local/bin/omarchy-cursor"))
}
fn lua_string(value: &str) -> String {
    serde_json::to_string(value).unwrap()
}
fn shell_arg(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\\''"))
}

pub fn bindings(config: &Config) -> Result<String> {
    config.validate()?;
    let bin = shell_arg(&binary()?);
    let mut text =
        String::from("-- Generated by Omarchy Cursor. Change shortcuts in Preferences.\n");
    text += "hl.layer_rule({ match = { namespace = \"^omarchy-cursor$\" }, no_anim = true, blur = false })\n";
    text += "hl.window_rule({ match = { class = \"^omarchy-cursor$\" }, float = true, size = { 640, 900 }, center = true, opacity = \"1 override 1 override\" })\n";
    for (key, label, command) in [
        (&config.toggle_key, "Toggle cursor highlight", "toggle"),
        (
            &config.magnify_key,
            "Toggle cursor magnifier",
            if config.magnify_hold {
                "magnify-on"
            } else {
                "magnify"
            },
        ),
        (&config.locate_key, "Locate cursor", "locate"),
    ] {
        text += &format!(
            "o.bind({}, {}, {})\n",
            lua_string(key),
            lua_string(label),
            lua_string(&format!("{bin} {command}"))
        );
    }
    if config.magnify_hold {
        text += &format!(
            "o.bind({}, \"Release cursor magnifier\", {}, {{ release = true }})\n",
            lua_string(&config.magnify_key),
            lua_string(&format!("{bin} magnify-off"))
        );
    }
    for (code, button) in [(272, "left"), (273, "right"), (274, "middle")] {
        for (release, state) in [(false, "down"), (true, "up")] {
            text += &format!(
                "hl.bind(\"mouse:{code}\", hl.dsp.exec_cmd({}), {{ non_consuming = true, transparent = true, ignore_mods = true, release = {release} }})\n",
                lua_string(&format!("{bin} click {button} {state}"))
            );
        }
    }
    Ok(text)
}

fn check_shortcuts(c: &Config) -> Result<()> {
    let binds: serde_json::Value = serde_json::from_str(&hypr::request("j/binds")?)?;
    for key in [&c.toggle_key, &c.magnify_key, &c.locate_key] {
        let pieces: Vec<_> = key.split('+').map(str::trim).collect();
        let name = pieces.last().unwrap();
        let mut mask = 0;
        for m in &pieces[..pieces.len() - 1] {
            mask |= match *m {
                "SUPER" => 64,
                "ALT" => 8,
                "CTRL" => 4,
                "SHIFT" => 1,
                _ => 0,
            };
        }
        if let Some(existing) = binds.as_array().into_iter().flatten().find(|b| {
            b["modmask"].as_i64() == Some(mask)
                && b["key"]
                    .as_str()
                    .is_some_and(|k| k.eq_ignore_ascii_case(name))
                && ![
                    "Toggle cursor highlight",
                    "Toggle cursor magnifier",
                    "Locate cursor",
                    "Release cursor magnifier",
                ]
                .contains(&b["description"].as_str().unwrap_or_default())
                && !b["arg"]
                    .as_str()
                    .unwrap_or_default()
                    .contains("omarchy-cursor")
        }) {
            anyhow::bail!(
                "Shortcut {key} is already assigned to {}. Choose a different shortcut in Preferences.",
                existing["description"]
            );
        }
    }
    Ok(())
}

pub fn update_bindings(c: &Config) -> Result<()> {
    check_shortcuts(c)?;
    let path = config_root()?.join("hypr/omarchy-cursor.lua");
    let previous = fs::read_to_string(&path).ok();
    fs::write(&path, bindings(c)?)?;
    if let Err(error) = reload() {
        if let Some(old) = previous {
            fs::write(path, old)?;
        } else {
            let _ = fs::remove_file(path);
        }
        let _ = reload();
        return Err(error);
    }
    Ok(())
}
fn reload() -> Result<()> {
    let result = hypr::request("/reload")?;
    ensure!(result.trim() == "ok", "Hyprland reload: {result}");
    let errors = hypr::request("/configerrors")?;
    ensure!(
        errors.trim().is_empty(),
        "Hyprland configuration errors: {errors}"
    );
    Ok(())
}
pub fn autostart_enabled() -> bool {
    config_root().is_ok_and(|r| {
        r.join("systemd/user/graphical-session.target.wants/omarchy-cursor.service")
            .exists()
    })
}
pub fn set_autostart(enabled: bool) -> Result<()> {
    let result = std::process::Command::new("systemctl")
        .args([
            "--user",
            if enabled { "enable" } else { "disable" },
            "omarchy-cursor.service",
        ])
        .output()?;
    ensure!(
        result.status.success(),
        "Could not change launch at login: {}",
        String::from_utf8_lossy(&result.stderr)
    );
    Ok(())
}
pub fn service_path() -> Result<PathBuf> {
    Ok(config_root()?.join("systemd/user/omarchy-cursor.service"))
}
fn desktop(daemon: bool) -> Result<String> {
    let bin = binary()?;
    let command = if daemon { "daemon" } else { "settings" };
    Ok(format!(
        "[Desktop Entry]\nType=Application\nName=Omarchy Cursor\nComment=Cursor highlight and magnifier\nExec=\"{}\" {command}\nIcon=omarchy-cursor\nTerminal=false\nCategories=Utility;Accessibility;\nStartupWMClass=omarchy-cursor\n",
        bin.display()
    ))
}
pub fn installed() -> bool {
    binary().is_ok_and(|p| p.exists())
}
pub fn install() -> Result<()> {
    let c = Config::load()?;
    check_shortcuts(&c)?;
    let was_running = crate::ipc::send("status").is_ok();
    let bin = binary()?;
    fs::create_dir_all(bin.parent().unwrap())?;
    let current = std::env::current_exe()?;
    if current != bin {
        let staging = bin.with_extension("new");
        fs::copy(current, &staging)?;
        fs::rename(staging, &bin)?;
    }
    let data = config::home()?.join(".local/share");
    fs::create_dir_all(data.join("applications"))?;
    fs::write(
        data.join("applications/omarchy-cursor.desktop"),
        desktop(false)?,
    )?;
    let icons = data.join("icons/hicolor/scalable/apps");
    fs::create_dir_all(&icons)?;
    fs::write(
        icons.join("omarchy-cursor.svg"),
        include_str!("../assets/omarchy-cursor.svg"),
    )?;
    let main = config_root()?.join("hypr/hyprland.lua");
    let original =
        fs::read_to_string(&main).context("Expected the Omarchy 4 Lua Hyprland configuration")?;
    let stamp = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();
    fs::copy(
        &main,
        main.with_extension(format!("lua.bak.cursor-{stamp}")),
    )?;
    let integration = config_root()?.join("hypr/omarchy-cursor.lua");
    let previous_integration = fs::read(&integration).ok();
    fs::write(&integration, bindings(&c)?)?;
    if !original.contains(START) {
        fs::write(
            &main,
            format!("{original}\n{START}\nrequire(\"hypr.omarchy-cursor\")\n{END}\n"),
        )?;
    }
    if let Err(error) = reload() {
        fs::write(&main, original)?;
        if let Some(previous) = previous_integration {
            fs::write(&integration, previous)?;
        } else {
            let _ = fs::remove_file(&integration);
        }
        let _ = reload();
        return Err(error);
    }
    c.save()?;
    let service = service_path()?;
    fs::create_dir_all(service.parent().unwrap())?;
    fs::write(
        service,
        format!(
            "[Unit]\nDescription=Omarchy Cursor highlight and magnifier\nPartOf=graphical-session.target\nAfter=graphical-session.target\n\n[Service]\nType=simple\nExecStart=\"{}\" daemon\nRestart=on-failure\nRestartSec=2\n\n[Install]\nWantedBy=graphical-session.target\n",
            bin.display()
        ),
    )?;
    let result = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output()?;
    ensure!(
        result.status.success(),
        "Could not register background service: {}",
        String::from_utf8_lossy(&result.stderr)
    );
    // An update must replace the running helper as well as its file on disk.
    if was_running {
        let _ = crate::ipc::send("quit");
        for _ in 0..100 {
            if crate::ipc::send("status").is_err() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
        let restarted = std::process::Command::new("systemctl")
            .args(["--user", "restart", "omarchy-cursor.service"])
            .output()?;
        ensure!(
            restarted.status.success(),
            "Could not restart cursor helper: {}",
            String::from_utf8_lossy(&restarted.stderr)
        );
        crate::ipc::ensure_daemon()?;
    }
    println!(
        "Installed {}\nShortcuts: {}, {}, {}",
        bin.display(),
        c.toggle_key,
        c.magnify_key,
        c.locate_key
    );
    Ok(())
}
pub fn uninstall() -> Result<()> {
    let _ = crate::ipc::send("quit");
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "stop", "omarchy-cursor.service"])
        .output();
    let root = config_root()?;
    let main = root.join("hypr/hyprland.lua");
    let text = fs::read_to_string(&main)?;
    if let (Some(start), Some(end)) = (text.find(START), text.find(END)) {
        let stamp = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();
        fs::copy(
            &main,
            main.with_extension(format!("lua.bak.cursor-uninstall-{stamp}")),
        )?;
        let mut updated = text.clone();
        updated.replace_range(start..end + END.len(), "");
        fs::write(&main, updated)?;
        reload()?;
    }
    set_autostart(false)?;
    if service_path()?.exists() {
        fs::remove_file(service_path()?)?;
    }
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output();
    for path in [
        root.join("hypr/omarchy-cursor.lua"),
        binary()?,
        config::home()?.join(".local/share/applications/omarchy-cursor.desktop"),
        config::home()?.join(".local/share/icons/hicolor/scalable/apps/omarchy-cursor.svg"),
    ] {
        if path.exists() {
            fs::remove_file(path)?;
        }
    }
    println!(
        "Omarchy Cursor removed. Preferences retained at {}",
        config::dir()?.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn all_mouse_bindings_are_non_consuming_and_include_release() {
        let s = bindings(&Config::default()).unwrap();
        assert_eq!(s.matches("non_consuming = true").count(), 6);
        assert_eq!(s.matches("release = true").count(), 3);
        assert!(!s.contains("hl.unbind"));
    }
}
